server:
  port: 8080
spring:
  profiles:
    active: dev

logging:
  file: pms.log
  path: /app/log

context:
  listener:
    classes: com.wj5633.pms.event.MyApplicationListener
  initializer:
    classes: com.wj5633.pms.initializer.MyApplicationContextInitializer

management:
  endpoints:
    web:
      exposure:
        include: '*'
